---
title: "Traitement des tendances interannuelles des indicateurs de qualité physico-chimiques"
output: html_notebook
params:  
  annee_debut: '2020'
  annee_fin: '2020'
  pvalue: 0.05
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(config) # Utilisation d'un fichier de configuration, cf  https://db.rstudio.com/best-practices/managing-credentials/#stored-in-a-file-with-config
library(tidyverse)
library(DBI) # pour les connexions aux BDD
library(RPostgres) # driver postgres
library(RMariaDB) # driver
library(RMySQL)
library(lubridate) # calcul sur les dates
library(mice) # Gestion des données manquantes
library(httr) #
library(jsonlite)
library(plotly) # Graphiques interactifs
library(leaflet) # Cartes interactives

library(Kendall) # Test de Mann-Kendall
library(trend) # Analyse des tendances temporelles
library(zoo) # Analyse de séries temporelles

suffixe <- if(params$annee_fin == params$annee_debut) paste("",params$annee_debut, sep="_") else paste("",params$annee_debut,params$annee_fin, sep="_")

```

```{r connexion bd}

con_referentiels <- dbConnect(RMariaDB::MariaDB(), default.file = '../.my.cnf', groups="mysql_oeb",
dbname = "eau_referentiels")

con_eau_data_traitees_nitrates <- dbConnect(RMariaDB::MariaDB(), default.file = '../.my.cnf', groups="mysql_oeb",
dbname = "eau_data_traitees_nitrates")

conf <- config::get("postgres_dev")

con_postgresql_dev <- DBI::dbConnect(odbc::odbc(),
                          Driver       = conf$driver,
                          servername   = conf$server,
                          UID = conf$uid,
                          PWD = conf$pwd,
                          Port = conf$port,
                          database = "eau",
                             encoding = "latin1")
```

```{r table_annuelle_Q90, fig.height=4, fig.width=12}


tbl(con_eau_data_traitees_nitrates, "eau_data_trt_ammonium_ce_ac") %>%
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1335_Valeur du Q90")%>%
  filter(Code_entitite_geographique %in% 	c('04207000','04207400'))%>%
  ggplot(aes(x = as.factor(Periode), y = Resultat, fill = Serie))+
  geom_bar(stat="identity")+
   facet_grid(Code_entitite_geographique ~ ., scales="free")

# Tendances par site (toutes années confondues)
resultatmk_site <- tbl(con_eau_data_traitees_nitrates, "eau_data_trt_phosphore_total_ce_ac") %>%
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1350_Valeur du Q90")%>%
  filter(Code_entitite_geographique %in% 	c('04162935') & Periode %in% c('2015','2016','2017','2018','2019'))%>%
  filter(!is.null(Resultat))%>%
  collect()%>%
  group_by(Code_entitite_geographique,Serie,CoordX_WGS84,CoordY_WGS84) %>%
  summarise(n_annees=n(),
            pvalue=ifelse(n_annees>=5,Kendall(as.integer(Periode),Resultat)$sl,NA),
            tendance=ifelse(n_annees>=5,Kendall(as.integer(Periode),Resultat)$tau,0),
            resultatmk= case_when(n_annees<5 ~ "Pas assez de données",
                                  n_annees>=5 & ! pvalue <= 0.05 ~ "NS",
                                  n_annees>=5 & pvalue <= 0.05 & tendance > 0 ~ "+",
                                  n_annees>=5 & pvalue <= 0.05 & tendance < 0 ~ "-"))

# Nb de sites par résultat
resultatmk_site %>%
  group_by(resultatmk)%>%
  summarise(n())

# Séries d'années continues
tbl(con_eau_data_traitees_nitrates, "eau_data_trt_ammonium_ce_ac") %>%
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1335_Valeur du Q90")%>%
  arrange(Code_entitite_geographique,Periode)%>%
  collect()%>%
  mutate(c(NA, ifelse(lag(Code_entitite_geographique) == Code_entitite_geographique), diff(as.integer(Periode)),NA))
  group_by(Code_entitite_geographique,Serie,CoordX_WGS84,CoordY_WGS84)%>%
  summarise(annee_debut=min(Periode),annee_fin=max(Periode))
```

```{r table_prelevements}

# top 10 Sites avec le plus de prélèvements
top_10_sites <- tbl(con_eau_data_traitees_nitrates, "eau_data_trt_ammonium_ce_ac") %>%
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1335_Concentration")%>%
  group_by(Code_entitite_geographique)%>%
  summarise(n_prel = n())%>%
  arrange(desc(n_prel))%>%
  collect()%>%
  top_n(10)%>%
  select(Code_entitite_geographique)

# Séries temporelles des résultats
tbl(con_eau_data_traitees_nitrates, "eau_data_trt_ammonium_ce_ac") %>%
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1335_Concentration") %>%
  mutate(Date = as.Date(Periode))%>%
  collect()%>%
  filter(Code_entitite_geographique %in% c('04207000','04178000','04195000','04177570'))%>%
  ggplot(aes(x = Date, y = Resultat, color = Serie))+
  geom_bar(stat="identity")+
  facet_grid(Code_entitite_geographique ~ ., scales="free")
  
# Décomposition d'une série temporelle

# Requête sur la table des résultats traités (en attendant d'avoir une table brute complète)
tbl(con_eau_data_traitees_nitrates, "eau_data_trt_ammonium_ce_ac") %>%
  # Garder la série des concentrations par prélèvement
  filter(Type_entitite_geographique_associee == "SITE" & Serie == "1335_Concentration") %>%
  # Récupérer une date de prélèvement
  mutate(Date = as.Date(Periode))%>%
  # Choix du CdSite
  filter(Code_entitite_geographique %in% 	c('04178000'))%>% 
  # Jusqu'ici la requête est faite sur le serveur, on récupère la donnée en mémoire
  collect() %>%
  # On complète les dates manquantes (jours sans prélèvements)
  complete(Date = seq.Date(min(Date), max(Date), by="day"))%>%
  # On ne garde que le résultat
  select(Resultat)%>%
  # Convertir en objet "série temporelle"
  ts(frequency = 365, start=c(1995,01))%>%
  # Simuler les résultats pour les jours sans prélèvements (valeur du dernier prélèvement)
  na.locf()%>%
  # Décomposition des séries temporelles
  decompose() %>%
  # Graphique de synthèse
  plot()
```

